
const DEFAULT_DATA={siteSettings:{schoolName:'Solid Dance School',tagline:'Move different.',address:'[ADDRESS]',phone:'+216 55 939 535 / +216 93 939 526',email:'tarakbouzid@gmail.com',hours:'[HOURS]',social:{instagram:'[INSTAGRAM_LINK]',facebook:'[FACEBOOK_LINK]',tiktok:'[TIKTOK_LINK]'}},hero:{type:'image',imageUrl:'',mobileImageUrl:'',videoUrl:'',posterUrl:'',headline:['SOLID','DANCE','SCHOOL'],subheadline:'Move different.',label:'Sfax / Tunisia',ctaText:'Discover classes',ctaUrl:'/cours',overlay:55,active:true},classes:[{id:'c1',name:'Contemporary',style:'Contemporary',age:'12+',level:'Open',teacher:'[TEACHERS_LIST]',schedule:'[CLASSES_LIST]',description:'A physical practice for musicality, weight, release and presence.'},{id:'c2',name:'Hip Hop',style:'Hip Hop',age:'10+',level:'All levels',teacher:'[TEACHERS_LIST]',schedule:'[CLASSES_LIST]',description:'Groove, foundations and freestyle in a focused studio rhythm.'},{id:'c3',name:'Kids Movement',style:'Movement',age:'6–11',level:'Beginner',teacher:'[TEACHERS_LIST]',schedule:'[CLASSES_LIST]',description:'A playful introduction to coordination, rhythm and confidence.'}],teachers:[{id:'t1',name:'[TEACHERS_LIST]',styles:'[TEACHERS_LIST]',bio:'[SCHOOL_STORY]',published:true}],schedules:[{id:'s1',day:'Monday',time:'[CLASSES_LIST]',className:'Contemporary',teacher:'[TEACHERS_LIST]',room:'Studio 01',availability:'[CLASSES_LIST]'}],events:[{id:'e1',title:'[EVENTS_LIST]',date:'',location:'[ADDRESS]',description:'[EVENTS_LIST]',url:'#',published:true}],news:[],videos:[],gallery:[{id:'g1',caption:'Movement / 01',published:true},{id:'g2',caption:'Practice / 02',published:true},{id:'g3',caption:'Rhythm / 03',published:true},{id:'g4',caption:'Presence / 04',published:true}],registrations:[],translations:{fr:{classes:'Cours',teachers:'Professeurs',schedule:'Horaires & tarifs',contact:'Contact',register:'Inscription',discover:'Découvrir les cours'},en:{classes:'Classes',teachers:'Teachers',schedule:'Schedule & rates',contact:'Contact',register:'Register',discover:'Discover classes'},ar:{classes:'الدروس',teachers:'الأساتذة',schedule:'الجدول والأسعار',contact:'اتصل بنا',register:'التسجيل',discover:'اكتشف الدروس'}}};
const clone=o=>JSON.parse(JSON.stringify(o));
function getData(){try{const stored=JSON.parse(localStorage.getItem('solidData')||'{}');const d=Object.assign(clone(DEFAULT_DATA),stored);d.siteSettings=Object.assign(clone(DEFAULT_DATA.siteSettings),stored.siteSettings||{});if(!d.siteSettings.phone||d.siteSettings.phone==='[NUMBER]')d.siteSettings.phone=DEFAULT_DATA.siteSettings.phone;if(!d.siteSettings.email||d.siteSettings.email==='[EMAIL]')d.siteSettings.email=DEFAULT_DATA.siteSettings.email;return d}catch{return clone(DEFAULT_DATA)}}
function saveData(data){localStorage.setItem('solidData',JSON.stringify(data));window.solidCloud?.save(data)}
function mergeData(){const d=getData(); return d}
function escapeHTML(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function applyTheme(){const saved=localStorage.getItem('solidTheme');const dark=saved?saved==='dark':matchMedia('(prefers-color-scheme: dark)').matches;document.body.classList.toggle('dark',dark);document.querySelectorAll('[data-theme]').forEach(b=>b.textContent=dark?'☼':'◐')}
function toggleTheme(){localStorage.setItem('solidTheme',document.body.classList.contains('dark')?'light':'dark');applyTheme()}
function setLang(lang){localStorage.setItem('solidLang',lang);document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;const d=getData().translations[lang]||{};if(d[key])el.textContent=d[key]})}
function renderHeader(){const page=document.body.dataset.page||'';const logoPath=document.body.dataset.admin?'../assets/solid-dance-school-logo-dark.png':'assets/solid-dance-school-logo-dark.png';return `<header class="site-header"><a class="logo" href="/"><img class="site-logo" src="${logoPath}" alt="Solid Dance School"></a><nav class="nav" id="siteNav"><a class="${page==='home'?'active':''}" href="/">Home</a><a class="${page==='classes'?'active':''}" data-i18n="classes" href="/cours">Classes</a><a class="${page==='teachers'?'active':''}" data-i18n="teachers" href="/professeurs">Teachers</a><a class="${page==='schedule'?'active':''}" data-i18n="schedule" href="/horaires-tarifs">Schedule</a><a href="/evenements">Events</a><a href="/galerie">Gallery</a><a data-i18n="contact" href="/contact">Contact</a></nav><div class="header-actions"><button class="icon-btn" data-theme aria-label="Toggle theme" onclick="toggleTheme()">◐</button><button class="icon-btn menu-btn" aria-label="Open menu" onclick="document.getElementById('siteNav').classList.toggle('open')">☰</button></div></header>`}
function renderFooter(){const s=getData().siteSettings;return `<footer class="footer"><div>© ${new Date().getFullYear()} ${escapeHTML(s.schoolName)}</div><div class="footer-links"><a href="/contact">${escapeHTML(s.email)}</a><a href="${escapeHTML(s.social.instagram)}">Instagram</a><a href="/admin/login">Admin</a></div></footer>`}
function setupCommon(){document.body.insertAdjacentHTML('afterbegin',renderHeader());document.body.insertAdjacentHTML('beforeend',renderFooter());applyTheme();setLang(localStorage.getItem('solidLang')||'fr');document.addEventListener('mousemove',e=>{const hero=document.querySelector('.hero-content');if(hero&&!matchMedia('(pointer:coarse)').matches){hero.style.transform=`translate(${(e.clientX/innerWidth-.5)*8}px,${(e.clientY/innerHeight-.5)*5}px)`}})}
function cardClass(c,i){return `<article class="class-card"><span class="card-num">0${i+1}</span><div class="eyebrow">${escapeHTML(c.style)}</div><h3 class="card-title">${escapeHTML(c.name)}</h3><div class="meta"><span class="tag">${escapeHTML(c.age)}</span><span class="tag">${escapeHTML(c.level)}</span></div><p>${escapeHTML(c.description)}</p></article>`}
function renderCards(){const el=document.querySelector('[data-classes]');if(!el)return;const d=getData();el.innerHTML=d.classes.map(cardClass).join('')}
function setupHero(){const h=getData().hero;if(!document.querySelector('.hero'))return;const media=document.querySelector('.hero-media');if(h.type==='video'&&h.videoUrl){media.classList.add('video-mode');media.innerHTML=`<video class="hero-image" autoplay muted loop playsinline poster="${escapeHTML(h.posterUrl)}" src="${escapeHTML(h.videoUrl)}"></video>`}else if(h.imageUrl){media.innerHTML=`<img class="hero-image" src="${escapeHTML(h.imageUrl)}" alt="Solid Dance School movement" onerror="this.remove()"><div class="hero-placeholder">MOVE</div>`}const c=document.querySelector('.hero-content');c.querySelector('.eyebrow').textContent=h.label;c.querySelector('h1').innerHTML=h.headline.map(escapeHTML).map(x=>`<span>${x}</span>`).join('');c.querySelector('.hero-sub p').textContent=h.subheadline;c.querySelector('.button').textContent=h.ctaText;c.querySelector('.button').href=h.ctaUrl}
function setupRegistration(){const form=document.querySelector('#registrationForm');if(!form)return;form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const data=getData();const entry=Object.fromEntries(new FormData(form));entry.id='R'+Date.now().toString().slice(-6);entry.date=new Date().toISOString();entry.status='New';data.registrations.unshift(entry);saveData(data);form.reset();document.querySelector('#registrationNotice').textContent='Merci. Votre demande a bien été enregistrée.';document.querySelector('#registrationNotice').classList.add('notice')})}
function setupCourses(){const wrap=document.querySelector('[data-course-list]');if(!wrap)return;const d=getData();const render=(filter='All')=>wrap.innerHTML=d.classes.filter(c=>filter==='All'||c.style===filter||c.age===filter||c.level===filter).map(cardClass).join('');const styles=['All',...new Set(d.classes.flatMap(c=>[c.style,c.age,c.level]))];document.querySelector('[data-course-filters]').innerHTML=styles.map((s,i)=>`<button class="filter ${i?'':'active'}" data-filter="${escapeHTML(s)}">${escapeHTML(s)}</button>`).join('');document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.filter)});render()}
function setupGallery(){document.querySelectorAll('.gallery-item').forEach((x,i)=>x.onclick=()=>{const l=document.querySelector('.lightbox');l.classList.add('open');l.querySelector('.lightbox-mark').textContent=`0${i+1}`;l.querySelector('p').textContent=x.dataset.caption});document.querySelector('.lightbox .close')?.addEventListener('click',()=>document.querySelector('.lightbox').classList.remove('open'));document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelector('.lightbox')?.classList.remove('open')})}
function setupPricing(){const n=document.querySelector('#classCount');if(!n)return;const f=document.querySelector('#familyCount');const out=document.querySelector('#priceOutput');const update=()=>{const classes=+n.value||0,fam=+f.value||1;out.textContent='[PRICES_LIST]';out.dataset.note=`${classes} classes / ${fam} member${fam>1?'s':''}`};n.oninput=f.oninput=update;update()}
function setupCountdown(){const e=getData().events.find(x=>x.published&&x.date);const out=document.querySelector('[data-countdown]');if(!out||!e)return;const tick=()=>{const diff=new Date(e.date)-new Date();if(diff<0)return;const days=Math.floor(diff/86400000);const hours=Math.floor(diff/3600000)%24;out.innerHTML=`<div><strong>${days}</strong><small>DAYS</small></div><div><strong>${hours}</strong><small>HOURS</small></div>`};tick();setInterval(tick,60000)}
function initPublic(){setupCommon();setupHero();renderCards();setupCourses();setupGallery();setupRegistration();setupPricing();setupCountdown()}


const adminSections={dashboard:'Dashboard',registrations:'Registrations',leads:'Leads / Interested',students:'Students / Classes',payments:'Payments',packs:'Packs & Pricing',classes:'Classes',schedules:'Schedules',teachers:'Teachers',events:'Events',news:'News',videos:'Videos',gallery:'Gallery',hero:'Hero / Homepage',pages:'Page content',settings:'Settings'};
function adminAuth(){if(sessionStorage.getItem('solidAdmin')!=='true'&&document.body.dataset.admin!=='login'){location.href='/admin/login';return false}return true}
function adminNav(active){return `<aside class="admin-sidebar"><a class="admin-brand" href="/admin"><img src="/assets/solid-dance-school-logo-dark.png" alt="Solid Dance School"><span>CONTROL CENTER</span></a><nav class="admin-nav">${Object.entries(adminSections).map(([k,v])=>`<a class="${k===active?'active':''}" href="${k==='dashboard'?'/admin':'/admin/'+k}">${v}</a>`).join('')}</nav><button class="admin-btn secondary" onclick="sessionStorage.removeItem('solidAdmin');location.href='/admin/login'">Log out</button></aside>`}
function toast(msg){const t=document.querySelector('.toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function adminStart(active){if(!adminAuth())return;document.querySelector('.admin-shell').insertAdjacentHTML('afterbegin',adminNav(active));document.querySelectorAll('[data-logout]').forEach(x=>x.onclick=()=>{sessionStorage.removeItem('solidAdmin');location.href='/admin/login'});}
function renderAdminTable(key,fields){const data=getData()[key]||[];const el=document.querySelector('[data-table]');if(!el)return;el.innerHTML=`<table class="data-table"><thead><tr>${fields.map(f=>`<th>${f}</th>`).join('')}<th>Actions</th></tr></thead><tbody>${data.map((row,i)=>`<tr>${fields.map(f=>`<td>${escapeHTML(row[f.toLowerCase()]||row[f]||'')}</td>`).join('')}<td><button class="admin-btn secondary" onclick="deleteRecord('${key}',${i})">Delete</button></td></tr>`).join('')}</tbody></table>`}
function deleteRecord(key,i){if(!confirm('Delete this item?'))return;const d=getData();d[key].splice(i,1);saveData(d);location.reload()}
function setupLogin(){const f=document.querySelector('#loginForm');if(!f)return;f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f);const user=fd.get('username');const pass=fd.get('password');const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(pass))),b=>b.toString(16).padStart(2,'0')).join('');if(user==='admin'&&hash==='cfd604ca2553893f192e2c5440d49a887cb3d9e62b8432613d88ac64a7e2f21d'){sessionStorage.setItem('solidAdmin','true');location.href='/admin'}else{const n=document.querySelector('#loginNotice');n.textContent='Invalid admin credentials.';n.classList.add('notice')}}}
function setupHeroAdmin(){const f=document.querySelector('#heroForm');if(!f)return;const h=getData().hero;for(const [k,v] of Object.entries(h)){const el=f.elements[k];if(el)el.type==='checkbox'?el.checked=v:el.value=Array.isArray(v)?v.join('\n'):v}f.onsubmit=e=>{e.preventDefault();const d=getData();const fd=new FormData(f);Object.keys(h).forEach(k=>{const el=f.elements[k];if(!el)return;d.hero[k]=el.type==='checkbox'?el.checked:el.value});d.hero.headline=String(d.hero.headline).split('\n').filter(Boolean);saveData(d);toast('Hero saved')}}
function setupCrud(key,fields){const f=document.querySelector('[data-crud-form]');if(!f)return;f.onsubmit=e=>{e.preventDefault();const d=getData();const row=Object.fromEntries(new FormData(f));row.id=key[0].toUpperCase()+Date.now().toString().slice(-5);d[key]=d[key]||[];d[key].push(row);saveData(d);f.reset();toast('Saved');renderAdminTable(key,fields)}}
function initAdmin(active){adminStart(active);if(active==='dashboard'){const d=getData();document.querySelector('#kpis').innerHTML=[['registrations',d.registrations.length],['new registrations',d.registrations.filter(x=>x.status==='New').length],['classes',d.classes.length],['teachers',d.teachers.length]].map(x=>`<div class="kpi"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}if(active==='hero')setupHeroAdmin();const maps={registrations:['registrations',['ID','Name','Phone','Email','Status']],classes:['classes',['Name','Style','Age','Level','Teacher']],schedules:['schedules',['Day','Time','Class','Teacher','Room']],teachers:['teachers',['Name','Styles','Bio']],events:['events',['Title','Date','Location','Published']],news:['news',['Title','Slug','Author','Published']],videos:['videos',['Title','Url','Published']],gallery:['gallery',['Caption','Published']]};if(maps[active]){renderAdminTable(...maps[active]);setupCrud(...maps[active])}}
