/* Solid Dance School Operations Desk
   One browser-persistent canonical registration record powers every derived view. */
(() => {
  const PACK_DEFAULTS = [
    {id:'pack1', name:'Pack 1', classesPerWeek:'1 course / week', classPrice:600, insurance:20, showFee:180, description:'Assurance + one course per week + year-end show fee.', active:true},
    {id:'pack2', name:'Pack 2', classesPerWeek:'2 courses + 3rd free / week', classPrice:1100, insurance:20, showFee:180, description:'Assurance + two courses with a third free + year-end show fee.', active:true}
  ];
  const PAGE_TITLES={dashboard:'DASHBOARD.',registrations:'REGISTRATIONS.',leads:'INTERESTED LEADS.',students:'STUDENTS.',payments:'PAYMENTS.',packs:'PACKS & PRICING.'};
  const money=n=>`${Number(n||0).toLocaleString('fr-FR')} DT`;
  const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const date=s=>s?new Date(s).toLocaleDateString('fr-FR'):'—';
  const isoToday=()=>new Date().toISOString().slice(0,10);
  const slug=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,'-');
  const id=prefix=>prefix+Date.now().toString().slice(-7);
  const clone=o=>JSON.parse(JSON.stringify(o));
  function rawData(){try{return JSON.parse(localStorage.getItem('solidData')||'{}')}catch{return {}}}
  function normalize(r){
    const row=Object.assign({id:id('R'),name:'',dob:'',phone:'',email:'',parentName:'',parentPhone:'',address:'',classId:'',className:'',danceStyle:'',ageGroup:'',level:'',trial:'',registrationDate:'',interestStatus:'',studentStatus:'lead',paymentMethod:'',paymentStatus:'unpaid',packId:'',notes:'',paymentPlan:{total:0,insurance:0,classPrice:0,showFee:0,payments:[]},audit:[]},r||{});
    row.paymentPlan=Object.assign({total:0,insurance:0,classPrice:0,showFee:0,payments:[]},row.paymentPlan||{}); row.paymentPlan.payments=Array.isArray(row.paymentPlan.payments)?row.paymentPlan.payments:[];
    row.audit=Array.isArray(row.audit)?row.audit:[];if(!row.registrationDate&&row.date)row.registrationDate=row.date;if(!row.className&&row.class)row.className=row.class;
    if(row.status==='Interested'&&!row.interestStatus)row.interestStatus='interested';
    if(row.status==='Not Interested'&&!row.interestStatus)row.interestStatus='not_interested';
    if(!row.interestStatus)row.interestStatus='pending';
    return row;
  }
  function data(){
    const d=rawData(); d.registrations=(d.registrations||[]).map(normalize); d.packs=Array.isArray(d.packs)&&d.packs.length?d.packs:clone(PACK_DEFAULTS); d.classes=d.classes||[]; d.paymentMethods=Array.isArray(d.paymentMethods)&&d.paymentMethods.length?d.paymentMethods:['Cash','Bank card','Cheque','Other']; d.teachers=d.teachers||[]; d.schedules=d.schedules||[]; d.opsVersion=2; return d;
  }
  function save(d){localStorage.setItem('solidData',JSON.stringify(d))}
  function record(d,r,action,detail=''){r.audit.unshift({id:id('A'),at:new Date().toISOString(),action,detail});}
  function packFor(d,r){return d.packs.find(p=>p.id===r.packId)||null}
  function totalFor(d,r){const p=packFor(d,r); if(p){r.paymentPlan.classPrice=Number(p.classPrice)||0;r.paymentPlan.insurance=Number(p.insurance)||0;r.paymentPlan.showFee=Number(p.showFee)||0;r.paymentPlan.total=r.paymentPlan.classPrice+r.paymentPlan.insurance+r.paymentPlan.showFee} return Number(r.paymentPlan.total)||0}
  function paidFor(r){return (r.paymentPlan.payments||[]).filter(p=>p.status==='paid').reduce((n,p)=>n+(Number(p.amount)||0),0)}
  function remainingFor(d,r){return Math.max(0,totalFor(d,r)-paidFor(r))}
  function syncPaymentStatus(d,r){const total=totalFor(d,r),paid=paidFor(r);r.paymentStatus=paid<=0?'unpaid':paid>=total&&total>0?'fully_paid':'partially_paid';if(paid>=total&&total>0)r.studentStatus='confirmed'}
  function statusLabel(v){return ({pending:'PENDING',interested:'INTERESTED',not_interested:'NOT INTERESTED',unpaid:'UNPAID',partially_paid:'PARTIALLY PAID',fully_paid:'FULLY PAID',comptant:'COMPTANT',facilite:'FACILITÉ',confirmed:'CONFIRMED'})[v]||String(v||'—').toUpperCase()}
  function status(v){return `<span class="ops-status ops-${slug(v)}">${statusLabel(v)}</span>`}
  function notify(msg){const t=document.querySelector('.toast');if(t){t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}}
  function nav(active){const groups=[['dashboard','Dashboard','index.html'],['registrations','Registrations','registrations.html'],['leads','Leads / Interested','leads.html'],['students','Students / Classes','students.html'],['payments','Payments','payments.html'],['packs','Packs & Pricing','packs.html'],['classes','Classes','classes.html'],['schedules','Schedules','schedules.html'],['teachers','Teachers','teachers.html'],['events','Events','events.html'],['news','News','news.html'],['videos','Videos','videos.html'],['gallery','Gallery','gallery.html'],['hero','Hero / Homepage','hero.html'],['pages','Page content','pages.html'],['settings','Settings','settings.html']]; return `<aside class="admin-sidebar ops-sidebar"><a class="ops-brand" href="index.html"><img src="../assets/solid-dance-school-logo-dark.png" alt="Solid Dance School"></a><div class="ops-rail-label">OPERATIONS DESK</div><nav class="admin-nav">${groups.map(g=>`<a class="${active===g[0]?'active':''}" href="${g[2]}">${g[1]}</a>`).join('')}</nav><a class="admin-btn secondary" href="../index.html">View site</a><button class="admin-btn secondary" onclick="sessionStorage.removeItem('solidAdmin');location.href='login.html'">Log out</button></aside>`}
  function auth(){if(sessionStorage.getItem('solidAdmin')!=='true'){location.href='login.html';return false}return true}
  function shell(active){if(!auth())return false;const root=document.querySelector('.ops-root');root.insertAdjacentHTML('afterbegin',nav(active));root.insertAdjacentHTML('beforeend','<div class="toast"></div><div class="ops-modal" id="opsModal"></div>');return true}
  function panel(title,body,cls=''){return `<section class="admin-panel ops-panel ${cls}"><div class="ops-panel-head"><h2>${title}</h2></div>${body}</section>`}
  function action(label,fn,cls='admin-btn'){return `<button type="button" class="${cls}" onclick="${fn}">${label}</button>`}
  function profile(idValue){const d=data(),r=d.registrations.find(x=>x.id===idValue);if(!r)return; const p=packFor(d,r); const payments=r.paymentPlan.payments||[]; const audit=r.audit||[]; openModal(`<div class="ops-modal-head"><span class="ops-kicker">PROFILE / ${esc(r.id)}</span><button class="modal-close" onclick="closeModal()">×</button></div><div class="profile-grid"><div><h2 class="profile-name">${esc(r.name||'Unnamed')}</h2><div class="profile-statuses">${status(r.interestStatus)} ${status(r.paymentMethod||'lead')} ${status(r.paymentStatus)}</div><dl class="ops-details"><dt>Phone</dt><dd>${esc(r.phone||'—')}</dd><dt>Email</dt><dd>${esc(r.email||'—')}</dd><dt>Parent</dt><dd>${esc(r.parentName||'—')} ${esc(r.parentPhone||'')}</dd><dt>Address</dt><dd>${esc(r.address||'—')}</dd><dt>Class</dt><dd>${esc(r.className||'—')}</dd><dt>Teacher</dt><dd>${esc((d.teachers.find(t=>t.id===r.teacherId)||{}).name||r.teacher||'—')}</dd><dt>Pack</dt><dd>${esc(p?.name||'—')}</dd></dl></div><div>${paymentSummary(d,r)}<h3>NOTES</h3><textarea id="profileNotes" class="ops-notes">${esc(r.notes||'')}</textarea>${action('Save notes',`saveNotes('${r.id}')`,'admin-btn')}<h3 class="ops-history-title">HISTORY</h3><div class="ops-history">${audit.slice(0,12).map(a=>`<div><time>${date(a.at)}</time><strong>${esc(a.action)}</strong><span>${esc(a.detail)}</span></div>`).join('')||'<p>No history yet.</p>'}</div></div></div>`,'profile');}
  function paymentSummary(d,r){const paid=paidFor(r),total=totalFor(d,r),remaining=Math.max(total-paid,0),pct=total?Math.min(100,Math.round(paid/total*100)):0;const next=(r.paymentPlan.payments||[]).filter(p=>p.status!=='paid'&&p.date).sort((a,b)=>a.date.localeCompare(b.date))[0];return `<div class="pay-summary"><div><small>TOTAL</small><strong>${money(total)}</strong></div><div><small>PAID</small><strong>${money(paid)}</strong></div><div><small>REMAINING</small><strong>${money(remaining)}</strong></div><div><small>NEXT PAYMENT</small><strong>${next?date(next.date):'—'}</strong></div><div class="progress"><span style="width:${pct}%"></span></div><p>${pct}% collected · ${statusLabel(r.paymentStatus)}</p></div>`}
  function openModal(html,cls=''){const m=document.querySelector('#opsModal');m.className=`ops-modal open ${cls}`;m.innerHTML=`<div class="ops-modal-card">${html}</div>`}
  function closeModal(){const m=document.querySelector('#opsModal');if(m)m.className='ops-modal'}
  window.closeModal=closeModal;window.openModal=openModal;window.viewProfile=profile;
  window.saveNotes=function(idValue){const d=data(),r=d.registrations.find(x=>x.id===idValue);if(!r)return;r.notes=document.querySelector('#profileNotes').value;record(d,r,'Notes updated');save(d);closeModal();notify('Notes saved');};
  function registrationRows(list,view='all'){return list.map(r=>`<tr><td><button class="link-button" onclick="viewProfile('${r.id}')">${esc(r.name||'Unnamed')}</button><small>${esc(r.id)}</small></td><td>${esc(r.phone||'—')}</td><td>${esc(r.className||'—')}</td><td>${esc(r.level||'—')}</td><td>${date(r.registrationDate)}</td><td>${status(r.interestStatus)}</td><td>${status(r.paymentStatus)}</td><td class="ops-actions">${view!=='not_interested'?action('✓ INTERESTED',`setInterest('${r.id}','interested')`,'admin-btn ops-positive'):''}${action('✕ NOT INTERESTED',`setInterest('${r.id}','not_interested')`,'admin-btn secondary')}${action('PROFILE',`viewProfile('${r.id}')`,'admin-btn secondary')}${action('REMOVE',`removeStudent('${r.id}')`,'admin-btn secondary')}</td></tr>`).join('')||'<tr><td colspan="8"><div class="notice">No records match this view.</div></td></tr>'}
  window.setInterest=function(idValue,next){const d=data(),r=d.registrations.find(x=>x.id===idValue);if(!r)return;r.interestStatus=next;record(d,r,next==='interested'?'Interest marked INTERESTED':'Interest marked NOT INTERESTED');save(d);renderPage('registrations')};
  function registrationPage(){const d=data();return `<div class="ops-toolbar ops-filters"><input id="regSearch" class="ops-search" placeholder="Search name, phone, email, ID, class" oninput="filterRegistrations()"><select id="regFilter" onchange="filterRegistrations()"><option value="all">All interest</option><option value="pending">Pending</option><option value="interested">Interested</option><option value="not_interested">Not Interested</option></select><select id="regPayment" onchange="filterRegistrations()"><option value="all">All payment status</option><option value="unpaid">Unpaid</option><option value="partially_paid">Partially paid</option><option value="fully_paid">Fully paid</option></select><select id="regClass" onchange="filterRegistrations()"><option value="all">All classes</option>${data().classes.map(c=>`<option>${esc(c.name)}</option>`).join('')}</select><select id="regPack" onchange="filterRegistrations()"><option value="all">All packs</option>${data().packs.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('')}</select><input id="regMonth" type="month" onchange="filterRegistrations()"></div>${panel('Registration pipeline',`<div class="table-wrap"><table class="data-table ops-table"><thead><tr><th>Name / ID</th><th>Phone</th><th>Class</th><th>Level</th><th>Registered</th><th>Interest</th><th>Payment</th><th>Actions</th></tr></thead><tbody id="registrationRows">${registrationRows(d.registrations)}</tbody></table></div>`)}<div class="ops-footnote">Records are never deleted by status changes. Every transition remains attached to the original registration ID.</div>`}
  window.filterRegistrations=function(){const d=data(),q=(document.querySelector('#regSearch')?.value||'').toLowerCase(),f=document.querySelector('#regFilter')?.value||'all',pay=document.querySelector('#regPayment')?.value||'all',cls=document.querySelector('#regClass')?.value||'all',pack=document.querySelector('#regPack')?.value||'all',month=document.querySelector('#regMonth')?.value||'';const rows=d.registrations.filter(r=>(f==='all'||r.interestStatus===f)&&(pay==='all'||r.paymentStatus===pay)&&(cls==='all'||r.className===cls)&&(pack==='all'||r.packId===pack)&&(!month||String(r.registrationDate||'').startsWith(month))&&[r.name,r.phone,r.email,r.id,r.className].some(v=>String(v||'').toLowerCase().includes(q)));document.querySelector('#registrationRows').innerHTML=registrationRows(rows,f)};
  function leadsPage(){const d=data(),rows=d.registrations.filter(r=>r.interestStatus==='interested');return panel('Interested leads',`<div class="ops-toolbar"><input class="ops-search" placeholder="Search interested leads" oninput="filterLeads()"></div><div class="table-wrap"><table class="data-table ops-table"><thead><tr><th>Name</th><th>Phone</th><th>Class</th><th>Level</th><th>Registration date</th><th>Interest</th><th>Payment</th><th>Action</th></tr></thead><tbody id="leadRows">${leadRows(rows)}</tbody></table></div>`)}
  function leadRows(rows){return rows.map(r=>`<tr><td><button class="link-button" onclick="viewProfile('${r.id}')">${esc(r.name)}</button></td><td>${esc(r.phone||'—')}</td><td>${esc(r.className||'—')}</td><td>${esc(r.level||'—')}</td><td>${date(r.registrationDate)}</td><td>${status(r.interestStatus)}</td><td>${status(r.paymentMethod||'unpaid')} ${status(r.paymentStatus)}</td><td class="ops-actions">${action('COMPTANT',`openCash('${r.id}')`,'admin-btn ops-positive')}${action('FACILITÉ',`openInstallments('${r.id}')`,'admin-btn')}${action('PROFILE',`viewProfile('${r.id}')`,'admin-btn secondary')}</td></tr>`).join('')||'<tr><td colspan="8"><div class="notice">No interested leads yet.</div></td></tr>'}
  window.filterLeads=function(){const q=(document.querySelector('.ops-search')?.value||'').toLowerCase();const d=data();document.querySelector('#leadRows').innerHTML=leadRows(d.registrations.filter(r=>r.interestStatus==='interested'&&[r.name,r.phone,r.email,r.className].some(v=>String(v||'').toLowerCase().includes(q))))};
  function paymentForm(r,kind){const d=data(),p=packFor(d,r),methodOptions=d.paymentMethods.map(m=>`<option>${esc(m)}</option>`).join(''),packOptions=d.packs.filter(x=>x.active!==false).map(x=>`<option value="${esc(x.id)}" data-total="${(Number(x.classPrice)||0)+(Number(x.insurance)||0)+(Number(x.showFee)||0)}" ${x.id===r.packId?'selected':''}>${esc(x.name)} · ${money((Number(x.classPrice)||0)+(Number(x.insurance)||0)+(Number(x.showFee)||0))}</option>`).join('');return `<div class="ops-modal-head"><span class="ops-kicker">${kind==='cash'?'COMPTANT':'FACILITÉ'} / ${esc(r.name)}</span><button class="modal-close" onclick="closeModal()">×</button></div><p class="modal-context">${esc(r.className||'No class')} · ${esc(p?.name||'Select a pack')} · Calculated total: <strong id="paymentTotal">${money(totalFor(d,r))}</strong></p><form onsubmit="confirmPayment(event,'${r.id}','${kind}')" class="form-grid ops-form"><div class="field full"><label>Pack / pricing</label><select name="packId" onchange="updatePaymentTotal(this)" required><option value="">Select pack</option>${packOptions}</select></div><div class="field"><label>Amount ${kind==='cash'?'paid':'/ installment'}</label><input name="amount" type="number" min="0" step="0.01" value="${kind==='cash'&&p?remainingFor(d,r):''}" required></div><div class="field"><label>Date of payment</label><input name="date" type="date" value="${isoToday()}" required></div><div class="field"><label>Payment method</label><select name="method">${methodOptions}</select></div><div class="field full"><label>Note</label><textarea name="note" placeholder="Payment note"></textarea></div><div class="field full ops-modal-actions">${action('Confirm payment',`confirmPayment(event,'${r.id}','${kind}')`,'admin-btn ops-positive')}${action('Cancel','closeModal()','admin-btn secondary')}</div></form>`}
  window.updatePaymentTotal=function(el){const opt=el.options[el.selectedIndex],out=document.querySelector('#paymentTotal');if(out)out.textContent=money(Number(opt?.dataset.total)||0)};
  window.openCash=function(idValue){const d=data(),r=d.registrations.find(x=>x.id===idValue);if(r)openModal(paymentForm(r,'cash'),'payment-modal')};
  window.openInstallments=function(idValue){const d=data(),r=d.registrations.find(x=>x.id===idValue);if(!r)return;openModal(`<div class="ops-modal-head"><span class="ops-kicker">FACILITÉ / ${esc(r.name)}</span><button class="modal-close" onclick="closeModal()">×</button></div>${paymentSummary(d,r)}<div class="installment-list">${(r.paymentPlan.payments||[]).map((p,i)=>`<div class="installment-row"><div><strong>${money(p.amount)}</strong><span>${date(p.date)} · ${esc(p.method||'—')}</span></div>${status(p.status)}<span>${esc(p.note||'')}</span><div class="ops-actions">${p.status!=='paid'?action('MARK PAID',`markPaymentPaid('${r.id}',${i})`,'admin-btn ops-positive'):''}${action('EDIT',`editPayment('${r.id}',${i})`,'admin-btn secondary')}${action('DELETE',`deletePayment('${r.id}',${i})`,'admin-btn secondary')}</div></div>`).join('')||'<p class="notice">No installments recorded yet.</p>'}</div>${action('ADD PAYMENT',`openAddInstallment('${r.id}')`,'admin-btn')}${action('Close','closeModal()','admin-btn secondary')}`,'payment-modal')};
  window.openAddInstallment=function(idValue){const d=data(),r=d.registrations.find(x=>x.id===idValue);if(r)openModal(paymentForm(r,'installment'),'payment-modal')};
  window.confirmPayment=function(ev,idValue,kind){ev.preventDefault();const form=ev.target.closest('form'),fd=new FormData(form),d=data(),r=d.registrations.find(x=>x.id===idValue);if(!r)return;if(fd.get('packId'))r.packId=fd.get('packId');totalFor(d,r);const amount=Number(fd.get('amount'))||0;if(kind==='cash'&&amount<remainingFor(d,r)){alert(`Comptant must cover the remaining balance of ${money(remainingFor(d,r))}.`);return}r.paymentMethod=kind==='cash'?'comptant':'facilite';if(kind==='cash')r.paymentPlan.payments.push({id:id('P'),amount,date:fd.get('date'),method:fd.get('method'),status:'paid',note:fd.get('note')||'',kind:'comptant'});else r.paymentPlan.payments.push({id:id('P'),amount:Number(fd.get('amount'))||0,date:fd.get('date'),method:fd.get('method'),status:'pending',note:fd.get('note')||'',kind:'installment'});syncPaymentStatus(d,r);r.studentStatus='confirmed';record(d,r,kind==='cash'?'Comptant payment confirmed':'Facilité payment plan updated',`${money(Number(fd.get('amount'))||0)} · ${fd.get('method')||''}`);save(d);closeModal();renderPage('leads');notify('Payment saved')};
  window.markPaymentPaid=function(idValue,index){const d=data(),r=d.registrations.find(x=>x.id===idValue),p=r?.paymentPlan.payments[index];if(!p)return;p.status='paid';p.paidAt=isoToday();syncPaymentStatus(d,r);record(d,r,'Payment marked paid',money(p.amount));save(d);openInstallments(idValue)};
  window.deletePayment=function(idValue,index){const d=data(),r=d.registrations.find(x=>x.id===idValue);if(!r)return;const removed=clone(r.paymentPlan.payments[index]);r.paymentPlan.payments.splice(index,1);syncPaymentStatus(d,r);record(d,r,'Payment deleted',`${money(removed.amount)} · ${removed.date||''} · ${removed.method||''}`);save(d);openInstallments(idValue)};
  window.editPayment=function(idValue,index){const d=data(),r=d.registrations.find(x=>x.id===idValue),p=r?.paymentPlan.payments[index];if(!p)return;openModal(`<div class="ops-modal-head"><span class="ops-kicker">EDIT PAYMENT</span><button class="modal-close" onclick="closeModal()">×</button></div><form onsubmit="savePaymentEdit(event,'${idValue}',${index})" class="form-grid ops-form"><div class="field"><label>Amount</label><input name="amount" type="number" step="0.01" value="${p.amount}" required></div><div class="field"><label>Date</label><input name="date" type="date" value="${p.date||''}" required></div><div class="field"><label>Method</label><input name="method" value="${esc(p.method||'')}"></div><div class="field"><label>Status</label><select name="status"><option value="paid" ${p.status==='paid'?'selected':''}>Paid</option><option value="pending" ${p.status!=='paid'?'selected':''}>Pending</option></select></div><div class="field full"><label>Note</label><textarea name="note">${esc(p.note||'')}</textarea></div><div class="field full">${action('Save payment',`savePaymentEdit(event,'${idValue}',${index})`,'admin-btn ops-positive')}</div></form>`,'payment-modal')};
  window.savePaymentEdit=function(ev,idValue,index){ev.preventDefault();const fd=new FormData(ev.target.closest('form')),d=data(),r=d.registrations.find(x=>x.id===idValue),p=r?.paymentPlan.payments[index];if(!p)return;const before=clone(p);['amount','date','method','status','note'].forEach(k=>{p[k]=k==='amount'?Number(fd.get(k))||0:fd.get(k)});syncPaymentStatus(d,r);record(d,r,'Payment edited',`${money(before.amount)} → ${money(p.amount)} · ${before.status} → ${p.status}`);save(d);openInstallments(idValue)};
  function studentRows(rows){return rows.map(r=>`<tr><td><button class="link-button" onclick="viewProfile('${r.id}')">${esc(r.name)}</button><small>${esc(r.id)}</small></td><td>${esc(r.className||'—')}</td><td>${date(r.registrationDate)}</td><td>${status(r.paymentStatus)}</td><td>${esc(r.phone||'—')}</td><td>${action('PROFILE',`viewProfile('${r.id}')`,'admin-btn secondary')}</td></tr>`).join('')||'<tr><td colspan="6"><div class="notice">No confirmed students yet.</div></td></tr>'}
  function studentsPage(){const d=data(),students=d.registrations.filter(r=>r.studentStatus==='confirmed');const classes=d.classes||[];return `${panel('All students',`<div class="ops-toolbar"><input class="ops-search" id="studentSearch" placeholder="Search students" oninput="filterStudents()">${action('ADD STUDENT','openAddStudent()','admin-btn')}</div><div class="table-wrap"><table class="data-table ops-table"><thead><tr><th>Student / ID</th><th>Class</th><th>Registration date</th><th>Payment</th><th>Phone</th><th>Action</th></tr></thead><tbody id="studentRows">${studentRows(students)}</tbody></table></div>`)}${panel('Class lists',classes.map(c=>{const rows=students.filter(r=>r.classId===c.id||r.className===c.name);return `<div class="class-list"><div><span class="ops-kicker">CLASS</span><h3>${esc(c.name)}</h3><p>${esc(c.teacher||'Teacher')} · ${esc(c.schedule||'Schedule')}</p></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Name</th><th>Registration date</th><th>Payment</th><th>Phone</th></tr></thead><tbody>${rows.map(r=>`<tr><td><button class="link-button" onclick="viewProfile('${r.id}')">${esc(r.name)}</button></td><td>${date(r.registrationDate)}</td><td>${status(r.paymentStatus)}</td><td>${esc(r.phone||'—')}</td></tr>`).join('')||'<tr><td colspan="4">No students assigned.</td></tr>'}</tbody></table></div></div>`}).join('')||'<div class="notice">Create classes from the Classes page first.</div>')}`}
  window.filterStudents=function(){const q=(document.querySelector('#studentSearch')?.value||'').toLowerCase();const d=data();document.querySelector('#studentRows').innerHTML=studentRows(d.registrations.filter(r=>r.studentStatus==='confirmed'&&[r.name,r.phone,r.email,r.id,r.className].some(v=>String(v||'').toLowerCase().includes(q))))};
  window.removeStudent=function(idValue){const d=data(),r=d.registrations.find(x=>x.id===idValue);if(!r)return;if(!confirm('Remove this student from the active student list? The registration record will remain.'))return;r.studentStatus='lead';record(d,r,'Student removed','Canonical registration retained');save(d);renderPage('students')};
  window.openAddStudent=function(){openModal(`<div class="ops-modal-head"><span class="ops-kicker">ADD CONFIRMED STUDENT</span><button class="modal-close" onclick="closeModal()">×</button></div><form onsubmit="saveNewStudent(event)" class="form-grid ops-form"><div class="field"><label>Full name</label><input name="name" required></div><div class="field"><label>Phone</label><input name="phone"></div><div class="field"><label>Email</label><input name="email" type="email"></div><div class="field"><label>Class</label><input name="className"></div><div class="field"><label>Level</label><input name="level"></div><div class="field"><label>Notes</label><input name="notes"></div><div class="field full">${action('Create student','saveNewStudent(event)','admin-btn ops-positive')}</div></form>`,'payment-modal')};
  window.saveNewStudent=function(ev){ev.preventDefault();const fd=new FormData(ev.target.closest('form')),d=data(),existing=d.registrations.find(x=>(fd.get('email')&&x.email===fd.get('email'))||(fd.get('phone')&&x.phone===fd.get('phone')&&fd.get('phone')));if(existing){existing.studentStatus='confirmed';existing.interestStatus='interested';existing.className=fd.get('className')||existing.className;existing.level=fd.get('level')||existing.level;existing.notes=fd.get('notes')||existing.notes;record(d,existing,'Existing record confirmed','Duplicate prevented');save(d);closeModal();renderPage('students');return}const r=normalize({id:id('R'),name:fd.get('name'),phone:fd.get('phone'),email:fd.get('email'),className:fd.get('className'),level:fd.get('level'),notes:fd.get('notes'),interestStatus:'interested',studentStatus:'confirmed',registrationDate:new Date().toISOString(),audit:[]});record(d,r,'Student created manually');d.registrations.push(r);save(d);closeModal();renderPage('students')};
  function paymentRows(rows){return rows.map(x=>`<tr><td><button class="link-button" onclick="viewProfile('${x.r.id}')">${esc(x.r.name)}</button></td><td>${esc(x.r.className||'—')}</td><td>${date(x.p.date)}</td><td>${money(x.p.amount)}</td><td>${esc(x.p.method||'—')}</td><td>${status(x.p.status)}</td><td>${esc(x.p.note||'')}</td></tr>`).join('')||'<tr><td colspan="7"><div class="notice">No payments match these filters.</div></td></tr>'}
  function allPayments(d){return d.registrations.flatMap(r=>(r.paymentPlan.payments||[]).map(p=>({r,p})));}
  function outstandingPayments(d){const rows=allPayments(d);return rows.concat(d.registrations.filter(r=>remainingFor(d,r)>0&&!rows.some(x=>x.r.id===r.id&&x.p.kind==='balance')).map(r=>({r,p:{id:'B'+r.id,amount:remainingFor(d,r),date:'',method:'—',status:'pending',note:'Outstanding balance',kind:'balance'}})))}
  function paymentsPage(){window.currentFilteredPayments=allPayments(data());return `${panel('Payment list',`<div class="ops-toolbar ops-filters"><input id="paySearch" class="ops-search" placeholder="Student, class, phone" oninput="filterPayments()"><input id="payMonth" type="month" onchange="filterPayments()"><select id="payView" onchange="filterPayments()"><option value="all">All payments</option><option value="outstanding">Outstanding</option><option value="installments">Installments</option></select><select id="payStatus" onchange="filterPayments()"><option value="all">All status</option><option value="paid">Paid</option><option value="pending">Pending</option></select><select id="payMethod" onchange="filterPayments()"><option value="all">All methods</option>${data().paymentMethods.map(m=>`<option>${esc(m)}</option>`).join('')}</select><select id="payClass" onchange="filterPayments()"><option value="all">All classes</option>${data().classes.map(c=>`<option>${esc(c.name)}</option>`).join('')}</select><select id="payTeacher" onchange="filterPayments()"><option value="all">All teachers</option>${data().teachers.map(t=>`<option value="${esc(t.id||t.name)}">${esc(t.name)}</option>`).join('')}</select><select id="payPack" onchange="filterPayments()"><option value="all">All packs</option>${data().packs.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('')}</select>${action('EXPORT CSV','exportPayments()','admin-btn')}${action('PRINT','printPayments()','admin-btn secondary')}</div><div class="table-wrap"><table class="data-table ops-table" id="paymentTable"><thead><tr><th>Student</th><th>Class</th><th>Payment date</th><th>Amount</th><th>Method</th><th>Status</th><th>Note</th></tr></thead><tbody id="paymentRows">${paymentRows(allPayments(data()))}</tbody></table></div>`)}`}
  window.filterPayments=function(){const d=data(),q=(document.querySelector('#paySearch')?.value||'').toLowerCase(),month=document.querySelector('#payMonth')?.value||'',view=document.querySelector('#payView')?.value||'all',st=document.querySelector('#payStatus')?.value||'all',method=document.querySelector('#payMethod')?.value||'all',cls=document.querySelector('#payClass')?.value||'all',teacher=document.querySelector('#payTeacher')?.value||'all',pack=document.querySelector('#payPack')?.value||'all';const source=view==='outstanding'?outstandingPayments(d):allPayments(d);const rows=source.filter(x=>(!q||[x.r.name,x.r.phone,x.r.email,x.r.id,x.r.className].some(v=>String(v||'').toLowerCase().includes(q)))&&(!month||String(x.p.date||'').startsWith(month))&&(view==='all'||(view==='outstanding'&&x.p.status!=='paid')||(view==='installments'&&x.p.kind==='installment'))&&(st==='all'||x.p.status===st)&&(method==='all'||x.p.method===method)&&(cls==='all'||x.r.className===cls)&&(teacher==='all'||String(x.r.teacherId||x.r.teacher||'')===teacher)&&(pack==='all'||x.r.packId===pack));window.currentFilteredPayments=rows;document.querySelector('#paymentRows').innerHTML=paymentRows(rows)};
  window.exportPayments=function(){const rows=window.currentFilteredPayments||allPayments(data()),csv=[['Student','Class','Payment Date','Amount','Method','Status','Note'],...rows.map(x=>[x.r.name,x.r.className,x.p.date,x.p.amount,x.p.method,x.p.status,x.p.note])].map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`solid-payments-${isoToday()}.csv`;a.click();URL.revokeObjectURL(a.href)};
  window.printPayments=function(){window.print()};
  function packsPage(){const d=data();return `${panel('Packs & pricing',`<div class="ops-toolbar">${action('NEW PACK','openPackForm()','admin-btn ops-positive')}</div><div class="pack-grid">${d.packs.map(p=>`<article class="pack-card"><div class="ops-kicker">${p.active?'ACTIVE':'INACTIVE'}</div><h3>${esc(p.name)}</h3><p>${esc(p.classesPerWeek||'')}</p><dl><dt>Classes</dt><dd>${money(p.classPrice)}</dd><dt>Insurance</dt><dd>${money(p.insurance)}</dd><dt>Show fee</dt><dd>${money(p.showFee)}</dd><dt>Total</dt><dd><strong>${money((Number(p.classPrice)||0)+(Number(p.insurance)||0)+(Number(p.showFee)||0))}</strong></dd></dl><p>${esc(p.description||'')}</p>${action('EDIT',`openPackForm('${p.id}')`,'admin-btn secondary')}</article>`).join('')}</div>`)}${panel('Payment methods',`<form class="ops-toolbar" onsubmit="saveMethods(event)"><input id="paymentMethods" class="ops-search" value="${esc(d.paymentMethods.join(', '))}" placeholder="Cash, Bank card, Cheque, Other"><button class="admin-btn ops-positive" type="submit">Save methods</button></form>`)} `}
  window.saveMethods=function(ev){ev.preventDefault();const d=data();d.paymentMethods=document.querySelector('#paymentMethods').value.split(',').map(x=>x.trim()).filter(Boolean);save(d);renderPage('packs');notify('Payment methods saved')};
  window.openPackForm=function(packId){const d=data(),p=d.packs.find(x=>x.id===packId)||{id:'',name:'',classesPerWeek:'',classPrice:0,insurance:20,showFee:180,description:'',active:true};openModal(`<div class="ops-modal-head"><span class="ops-kicker">${packId?'EDIT PACK':'NEW PACK'}</span><button class="modal-close" onclick="closeModal()">×</button></div><form onsubmit="savePack(event,'${packId||''}')" class="form-grid ops-form"><div class="field"><label>Pack name</label><input name="name" value="${esc(p.name)}" required></div><div class="field"><label>Classes</label><input name="classesPerWeek" value="${esc(p.classesPerWeek)}"></div><div class="field"><label>Annual insurance</label><input name="insurance" type="number" value="${p.insurance}"></div><div class="field"><label>Annual class price</label><input name="classPrice" type="number" value="${p.classPrice}"></div><div class="field"><label>Show / event fee</label><input name="showFee" type="number" value="${p.showFee}"></div><div class="field"><label><input name="active" type="checkbox" ${p.active?'checked':''}> Active</label></div><div class="field full"><label>Description</label><textarea name="description">${esc(p.description)}</textarea></div><div class="field full">${action('Save pack',`savePack(event,'${packId||''}')`,'admin-btn ops-positive')}</div></form>`,'payment-modal')};
  window.savePack=function(ev,packId){ev.preventDefault();const fd=new FormData(ev.target.closest('form')),d=data(),p=packId?d.packs.find(x=>x.id===packId):{id:id('PK')};Object.assign(p,{name:fd.get('name'),classesPerWeek:fd.get('classesPerWeek'),insurance:Number(fd.get('insurance'))||0,classPrice:Number(fd.get('classPrice'))||0,showFee:Number(fd.get('showFee'))||0,active:fd.get('active')==='on',description:fd.get('description')||''});if(!packId)d.packs.push(p);save(d);closeModal();renderPage('packs');notify('Pack saved')};
  function dashboardPage(){const d=data(),all=d.registrations,interested=all.filter(r=>r.interestStatus==='interested'),notInterested=all.filter(r=>r.interestStatus==='not_interested'),confirmed=all.filter(r=>r.studentStatus==='confirmed'),unpaid=confirmed.filter(r=>r.paymentStatus!=='fully_paid'),paid=confirmed.filter(r=>r.paymentStatus==='fully_paid'),facilite=all.filter(r=>r.paymentMethod==='facilite'),revenue=all.reduce((n,r)=>n+paidFor(r),0),outstanding=all.reduce((n,r)=>n+remainingFor(d,r),0);const kpis=[['REGISTRATIONS',all.length],['INTERESTED',interested.length],['NOT INTERESTED',notInterested.length],['CONFIRMED STUDENTS',confirmed.length],['UNPAID',unpaid.length],['PAID',paid.length],['FACILITÉ',facilite.length],['REVENUE',money(revenue)],['OUTSTANDING',money(outstanding)]];return `<div class="ops-kpis">${kpis.map(x=>`<div class="ops-kpi"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</div>${panel('Recent registrations',`<div class="table-wrap"><table class="data-table ops-table"><thead><tr><th>Name</th><th>Registered</th><th>Interest</th><th>Payment</th><th>Action</th></tr></thead><tbody>${all.slice().sort((a,b)=>b.registrationDate.localeCompare(a.registrationDate)).slice(0,8).map(r=>`<tr><td><button class="link-button" onclick="viewProfile('${r.id}')">${esc(r.name||'Unnamed')}</button></td><td>${date(r.registrationDate)}</td><td>${status(r.interestStatus)}</td><td>${status(r.paymentStatus)}</td><td>${action('PROFILE',`viewProfile('${r.id}')`,'admin-btn secondary')}</td></tr>`).join('')||'<tr><td colspan="5">No registrations yet.</td></tr>'}</tbody></table></div>`)}${panel('Workflow',`<div class="ops-flow"><span>PUBLIC REGISTRATION</span><b>↓</b><span>REGISTRATIONS</span><b>→</b><span>LEADS</span><b>→</b><span>COMPTANT / FACILITÉ</span><b>→</b><span>STUDENT</span></div>`)}`}
  function renderPage(page){const root=document.querySelector('.ops-content');if(!root)return;root.innerHTML=`<div class="ops-top"><div><span class="ops-kicker">SOLID / OPERATIONS</span><h1 class="admin-title">${PAGE_TITLES[page]||page.toUpperCase()}</h1></div>${page==='dashboard'?'<span class="ops-date">'+new Date().toLocaleDateString('fr-FR',{dateStyle:'full'})+'</span>':''}</div>${page==='dashboard'?dashboardPage():page==='registrations'?registrationPage():page==='leads'?leadsPage():page==='students'?studentsPage():page==='payments'?paymentsPage():page==='packs'?packsPage():''}`}
  window.renderPage=renderPage;
  window.opsInit=function(page){if(!shell(page))return;renderPage(page)};
})();
